---

influxdb_version: latest

influxdb_service:
  # supported log levels are debug, info, and error (default info)
  log:
    level: debug

influxdb_organizations:
  main-org:
    state: create
    description: Main organization
  guest-org:
    state: create

influxdb_users:
  admin:
    state: create
    operator: false
    organization:
      name: main-org
      admin: true
    password: LA9NMTb6WZ285zPGPgyUJEucuJUjr6W7

...
