---

- name: detect extracted binary file for influxdb3
  ansible.builtin.stat:
    path: "{{ influxdb_install_paths.core }}/influxdb3"
  register: stat_influxdb_file_binary

- name: core
  when:
    - stat_influxdb_file_binary.stat is defined
    - not stat_influxdb_file_binary.stat.exists | default('false') | bool
  block:

    - name: propagate influx core archive
      # when:
      #   - stat_influxdb_file_binary.stat is defined
      #   - not stat_influxdb_binary.stat.exists | default('false') | bool
      ansible.builtin.copy:
        src: "{{ influxdb_local_tmp_directory }}/{{ influxdb_download_artifact }}"
        dest: "{{ influxdb_install_paths.core }}/"
        remote_src: "{{ 'true' if influxdb_direct_download else 'false' }}"

    - name: extract influxdb archiv
      # when:
      #   - stat_influxdb_file_binary.stat is defined
      #   - not stat_influxdb_binary.stat.exists | default('false') | bool
      ansible.builtin.unarchive:
        src: "{{ influxdb_install_paths.core }}/{{ influxdb_release.files.core }}"
        dest: "{{ influxdb_install_paths.core }}/"
        owner: "{{ influxdb_system_user }}"
        group: "{{ influxdb_system_group }}"
        copy: false
        extra_opts:
          - --strip-components=1

    - name: remove influx core archive
      ansible.builtin.file:
        path: "{{ influxdb_install_paths.core }}/{{ influxdb_download_artifact }}"
        state: absent

- name: detect activated influxdb3
  ansible.builtin.stat:
    path: "/usr/bin/influxdb3"
  register: stat_influxdb_activated

- name: detect, if influx {{ influxdb_version }} activated
  ansible.builtin.set_fact:
    influxdb_must_activated: "{{ not stat_influxdb_activated.stat | bodsch.core.linked_version(install_path=influxdb_install_paths.core, version=influxdb_version) }}"

- name: activate influx
  when:
    - stat_influxdb_file_binary.stat is defined
    - stat_influxdb_file_binary.stat.exists | default('false') | bool
    - influxdb_must_activated | bool
  block:
    - name: create link to influxdb3 binary
      ansible.builtin.file:
        src: "{{ influxdb_install_paths.core }}/influxdb3"
        dest: "/usr/bin/influxdb3"
        state: link
        force: true
      notify:
        - restart influxdb
