---

- name: create link to influxd binary
  file:
    src: "{{ influxdb_install_path }}/influxd"
    dest: /usr/bin/influxd
    state: link
    force: true
  notify:
    - restart service

- name: create link to influx binary
  file:
    src: "{{ influxdb_install_path }}/influx"
    dest: /usr/bin/influx
    state: link
    force: true

- name: create influxdb data directory
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ influxdb_system_user }}"
    group: "{{ influxdb_system_group }}"
    mode: 0755
  loop:
    - "{{ influxdb_storage_dir }}"
    - "{{ influxdb_storage_dir }}/meta"
    - "{{ influxdb_storage_dir }}/data"
    - "{{ influxdb_storage_dir }}/wal"

- name: systemd
  block:

    - name: create systemd service unit
      template:
        src: "init/systemd/influxdb.service.j2"
        dest: "{{ systemd_lib_directory }}/influxdb.service"
        owner: root
        group: root
        mode: 0644
      notify:
        - systemd daemon reload
        - restart service

    - name: create influxdb run configuration
      template:
        src: "default/influxdb.j2"
        dest: "{{ influxdb_defaults_directory }}/influxdb"
        force: true
        owner: root
        group: "{{ influxdb_system_group }}"
        mode: 0640
      notify:
        # - validate config
        - reload service
  when:
    - ansible_service_mgr | lower == "systemd"

- name: openrc
  block:
    - name: create openrc service configuration
      template:
        src: "init/openrc/conf.d/influxdb.j2"
        dest: "/etc/conf.d/influxdb"
        owner: root
        group: root
        mode: 0644

    - name: create openrc init configuration
      template:
        src: "init/openrc/init.d/influxdb.j2"
        dest: "/etc/init.d/influxdb"
        owner: root
        group: root
        mode: 0750
  when:
    - ansible_service_mgr | lower == "openrc"

- name: create local facts
  template:
    src: ansible_facts.j2
    dest: /etc/ansible/facts.d/influxdb.fact
    mode: 0755

...
