---

- name: prepare
  ansible.builtin.include_tasks: prepare.yml

- name: download archives
  ansible.builtin.include_tasks: download.yml

- name: install
  ansible.builtin.include_tasks: install.yml

- name: configure
  ansible.builtin.include_tasks: configure/main.yml

- name: service
  ansible.builtin.include_tasks: service.yml

...
