---

- name: prepare
  include_tasks: prepare.yml

- name: download archives
  include_tasks: download.yml
  when:
    - not influxdb_exists or
      not influxdb_client_exists

- name: install
  include_tasks: install.yml

- name: configure
  include_tasks: configure/main.yml

#- name: service
#  include_tasks: service.yml

...
