---

- name: restart {{ influxdb_release.binaries.core }} if needed
  ansible.builtin.meta: flush_handlers

- name: ensure {{ influxdb_release.binaries.core }} is enabled on boot
  become: true
  ansible.builtin.service:
    name: "{{ influxdb_release.binaries.core }}"
    enabled: true
    state: started

...
