---

- name: systemd daemon reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    force: true
  when:
    - ansible_service_mgr | lower == "systemd"

- name: start service
  ansible.builtin.service:
    name: influxdb
    state: started

- name: restart service
  ansible.builtin.service:
    name: influxdb
    state: restarted

- name: reload service
  ansible.builtin.service:
    name: influxdb
    state: reloaded

...
