---

influxdb_service:
  # supported log levels are debug, info, and error (default info)
  log:
    level: error

influxdb_organizations:
  main-org:
    state: create
    description: Main organization
  guest-org:
    state: create

influxdb_users:
  admin:
    state: create
    operator: false
    organization:
      name: main-org
      admin: true
    password: LA9NMTb6WZ285zPGPgyUJEucuJUjr6W7

  admin01:
    state: create
    organization:
      name: main-org
    password: secretPassword
    permissions: []

  guest01:
    state: create
    organization:
      name: guest-org
    password: secretPassword

influxdb_buckets:
  bucket01:
    state: create
    description: First bucket
    organization:
      name: main-org
    retention: 1d
  bucket02:
    description: Second bucket
    organization:
      name: main-org

...
